apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.app_name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
      - name: {{ .Values.app_name }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Values.database.db_host }}
        - name: WORDPRESS_DB_NAME
          value: {{ .Values.database.db_name }}
        - name: WORDPRESS_DB_USER
          value: {{ .Values.database.db_user }}
        - name: WORDPRESS_DB_PASSWORD       
          value: {{ .Values.database.db_pass }}  
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/src/wordpress/wp-content/uploads
            name: nfs-mount
            subPath: {{ .Values.app_name }}/{{ .Values.env }}/uploads
          - mountPath: /usr/src/wordpress/.htaccess
            name: nfs-mount
            subPath: {{ .Values.app_name }}/{{ .Values.env }}/htaccess
      imagePullSecrets:
        - name: cr-auth
      volumes:
      - name: nfs-mount
        persistentVolumeClaim:
          claimName: {{ .Values.app_name }}