apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: {{ .Values.app_name }}
data: 
  auth: {{ .Values.basic_auth }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cr-auth
  namespace: {{ .Values.app_name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.cr_auth }}
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  namespace: {{ .Values.app_name }}
data:
  azurestorageaccountkey: {{ .Values.azstaccountkey }}
  azurestorageaccountname: {{ .Values.azstaccountname }}