apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: {{ .Values.app.namespace }}
data: 
  auth: {{ .Values.auth.basic_auth }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cr-auth
  namespace: {{ .Values.app.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.auth.cr_auth }}
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  namespace: {{ .Values.app.namespace }}
data:
  azurestorageaccountkey: {{ .Values.auth.azstaccountkey }}
  azurestorageaccountname: {{ .Values.auth.azstaccountname }}