apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.app_name }}
spec:
  selector:
    app: {{ .Values.app_name }}
  ports:
  - name: http
    port: 80
    targetPort: 80