apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
data:
  auth: $BASIC_AUTH
---
apiVersion: v1
kind: Secret
metadata:
  name: cr-auth
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: $CR_AUTH
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
data:
  azurestorageaccountkey: $AZSTACCOUNTKEY
  azurestorageaccountname: $AZSTACCOUNTNAME
