app_name: $CI_COMMIT_BRANCH
basic_auth: $BASIC_AUTH
cr_auth: $CR_AUTH
azstaccountkey: $AZSTACCOUNTKEY
azstaccountname: $AZSTACCOUNTNAME
cr_repo: $CR_REPO
hosts:
  - app1.example.io
  - app2.example.io
