app:
  name: $APP_NAME
  hosts: $SITE_URL
  pvc_path: $APP_ENV_LOCATION

pvc:
  share: $PVC_FILESHARE

image:
  registry: $CR_REPO
  repository: $APP_LOCATION
  tag: $IMAGE_TAG

database:
  db_host: $DB_HOST
  db_name: $DB_NAME
  db_user: $DB_ADMIN
  db_pass: $DB_PASS
