app:
  name: $APP_NAME
  hosts: $SITE_URL
  pvc_path: $ENV_APP_DIR

pvc:
  share: $FS_NAME

image:
  registry: $CR_REPO
  repository: $CI_PROJECT_NAME
  tag: $IMAGE_TAG

database:
  db_host: $DB_HOST
  db_name: $DB_NAME
  db_user: $DB_ADMIN
  db_pass: $DB_PASS
